story=  '''Natural composite materials exist since first ancient builder used straw to reinforce mud bricks. In 12th century, Mongols made archery bow by using cattle tendons, horn, bamboo, silk, and natural pine resin. In late 1800s, canoe builders glued together layers of kraft paper with shellac to get paper laminates. Though the concept was successful but performance of materials was not good. Between 1870 and 1890, a revolution took place with the development of first synthetic resin, called polyester by American Cyanamid and DuPont. During same period, Owens-Illinois began weaving glass fiber into a textile fabric on a commercial basis.
From 1934 and 1936, Ray Green, combined these two new products for making small boats and this was the beginning of composite era. Composites industry began in late 1940s and expanded rapidly through 1950-55s. Boats, car bodies, truck parts, aircraft components, underground storage tanks, buildings are some of the products which were made at that time.
Composite material generally consists of two materials: one is the matrix and other is reinforcement, final product retains properties of each constituent. Wood is an example of natural composite material, made up of cellulose (reinforcement), and lignin (matrix). Other examples of natural composites are bones, teeth, plant leaves and bird feathers.
1.1.2	Examples of Natural Composite Materials

Some of the examples of natural composite materials are given below:
 
Wood: Wood is an excellent example of natural composite in which cellulose fibers are held together by lignin. Closely packed cellulose molecule provides higher density and strength in the composites. Presence of cellulose is responsible for adequate strength in plants and trees.
Mud Bricks: The most primitive man made composite material is mud brick, made of straw and mud for construction use. Mud has lower tensile strength and fail upon bending. When straw is embedded into mud and allowed to dry, resulting mud brick resists both compressive and tensile forces, making an excellent building material. Individual bricks of mud can be made and then laid by using a mud mortar in a similar way to laying bricks or entire wall can be formed by continuous molding process so that a wall is one big brick effectively.
'''